CREATE TABLE STATE(
    STATE_ID SERIAL,
    NAME VARCHAR(30),
    PRIMARY KEY (STATE_ID)

);


CREATE TABLE COLOR(
    COLOR_ID SERIAL,
    NAME VARCHAR(30),
    PRIMARY KEY (COLOR_ID)
);

CREATE TABLE TEAM( 
    TEAM_ID SERIAL,
    NAME VARCHAR(30),
    STATE_ID INT NOT NULL,
    COLOR_ID INT NOT NULL,
    WINS INT,
    LOSSES INT,
    PRIMARY KEY (TEAM_ID),
    FOREIGN KEY (STATE_ID) REFERENCES STATE(STATE_ID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (COLOR_ID) REFERENCES COLOR(COLOR_ID) ON DELETE SET NULL ON UPDATE CASCADE
);





CREATE TABLE PLAYER(
    PLAYER_ID SERIAL,
    TEAM_ID INT,
    UNIFORM_NUM VARCHAR(30),
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    MPG INT,
    PPG INT,
    RPG INT,
    APG INT,
    SPG DOUBLE PRECISION,
    BPG DOUBLE PRECISION,
    PRIMARY KEY (PLAYER_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE SET NULL ON UPDATE CASCADE
);


